Add links to speakers' profile
fossasia/2016.fossasia.org pull request #127
Opened 2017-12-08 06:06 UTC by Ploypiti

Issue **#126** [Add link to speakers' profile](https://github.com/fossasia/2016.fossasia.org/issues/126)

2017-12-08 13:38 UTC, mariobehling commented on index.html
> +									<li><a target="_self" href="http://twitter.com/fossasia"><i class="icon social_twitter"></i></a></li>
why are you changing this? Should not be changed.

2017-12-08 13:40 UTC, mariobehling requested changes
Too many changes, many are good, but a number of changes are not suitable. You are changing the drop down menu links for other events. They are correct. As you are changing a lot of things that are not related to the speakers profile we cannot accept this PR. You aren't doing what the issue and the description says. Please submit a clean PR that is related to each change and make it easier to review by sticking exactly to what is mentioned in an issue.

2017-12-08 13:45 UTC, Ploypiti commented
I _did not_ change anything besides adding link to speakers' profile and tidy up the code (it messed up when I add the code) I wonder _when_ did I change the dropdown menu?

2017-12-08 14:45 UTC, mariobehling commented
Please tidy up the code in a separate PR.

2017-12-08 14:49 UTC, Ploypiti commented
I know, I'll send a not-tidied code later as I can't use my laptop right
now, however I insist I didn't make any change beyond the task.

Regards

Ploypiti

On Dec 8, 2017 21:45, "Mario Behling" <notifications@github.com> wrote:

> Please tidy up the code in a separate PR.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/fossasia/2016.fossasia.org/pull/127#issuecomment-350280251>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AfGnOg3y54vbHCIBC-Psk1g6X_9QQqzSks5s-UuJgaJpZM4Q6o52>
> .
>

2017-12-09 05:57 UTC, akshatnitd requested changes
I can see that you have made a whole lot of changes, out of which many are not required. I would suggest you to close this PR, sync your code with original repo, make changes and submit a fresh PR :)

2017-12-09 07:35 UTC, closed without merging