Added Profile Links
fossasia/2016.fossasia.org pull request #139
Opened 2017-12-22 05:45 UTC by arjunpandey2003

Issue #138

2017-12-22 19:37 UTC, akshatnitd requested changes
Also add

2017-12-22 19:37 UTC, akshatnitd commented on index.html
> +												<a href="geekfeminism.wikia.com/wiki/Cat_Allman"><i class="icon fa fa-external-link"></i></a>
Add `http` before the link

2017-12-22 19:37 UTC, akshatnitd commented on index.html
> +												<a href="www.bytebot.net/"><i class="icon fa fa-external-link"></i></a>
Add `http` before link

2017-12-22 19:37 UTC, akshatnitd commented on index.html
> +											<a href="www.bernardleong.com/biography"><i class="icon fa fa-external-link"></i></a>
Add `http` before link

2017-12-23 07:14 UTC, akshatnitd requested changes

2017-12-23 07:14 UTC, akshatnitd commented on index.html
> +											<a href="www.bernardleong.com/biography"><i class="icon fa fa-external-link"></i></a>
@arjunpandey2003 You forgot to make change in this link. Also, please squash the commits

2017-12-23 17:13 UTC, arjunpandey2003 commented
@akshatnitd please review again

2017-12-23 17:16 UTC, arjunpandey2003 commented
@mariobehling please review

2017-12-23 18:03 UTC, akshatnitd requested changes
@arjunpandey2003 Please squash the commits. Refer this for help if needed, https://gist.github.com/patik/b8a9dc5cd356f9f6f980

2017-12-23 18:05 UTC, arjunpandey2003 commented
@akshatnitd i have made these changes on the online editor so how should i squash

2017-12-23 18:20 UTC, isuruAb reviewed
Please squash your commits

2017-12-23 18:21 UTC, arjunpandey2003 commented
@isuruAb  i have made these changes on the online editor so how should i squash

2017-12-23 18:35 UTC, arjunpandey2003 commented
@akshatnitd @isuruAb Squashed

2017-12-23 18:37 UTC, arjunpandey2003 commented
Please approve

2017-12-23 18:37 UTC, akshatnitd approved these changes
Great work! :smiley:
Merging :rocket:

2017-12-23 18:38 UTC, merged

2017-12-23 18:42 UTC, arjunpandey2003 commented
Thanks @akshatnitd !