Fixed Alignment problem and Indentation
fossasia/2016.fossasia.org pull request #142
Opened 2017-12-25 13:09 UTC by duttaditya18

* Fixed Alignment Problem.
* Fixed Indentation.
* Fixed #141 

***Preview Link : https://duttaditya18.github.io/2016.fossasia.org/***

---

2017-12-25 17:01 UTC, anshumanv requested changes
Many of your changes are not indented correctly, please fix.

2017-12-26 04:56 UTC, NaviRocker requested changes
Try to Fix Indentation.

2017-12-26 09:02 UTC, duttaditya18 commented
@anshumanv @naveentherocker I fixed the indentation of almost the whole `index.html`.
Spent quite a bit of time on it! Please check it out!

2017-12-26 09:14 UTC, samyakbvs approved these changes

2017-12-26 09:57 UTC, anshumanv reviewed
I've pointed out some more, there are others too, please see diff.

2017-12-26 09:57 UTC, anshumanv commented on index.html
> +                                                <a href="https://www.facebook.com/davide.storti.73"><i class="icon social_facebook"></i></a>
Still not indented correctly.

2017-12-26 09:57 UTC, anshumanv commented on index.html
> +	                                            <a target="default" href="https://www.facebook.com/mkmcqd" target="default"><i class="icon social_facebook"></i></a>
same

2017-12-26 09:57 UTC, anshumanv commented on index.html
> +            									<a href="https://www.instagram.com/bytebot/"><i class="icon social_instagram"></i></a>
same

2017-12-26 10:14 UTC, duttaditya18 commented
@anshumanv Fixed!

2017-12-26 10:43 UTC, duttaditya18 commented
Ping @anshumanv

2017-12-26 11:14 UTC, anshumanv approved these changes

2017-12-26 13:54 UTC, NaviRocker approved these changes
LGTM

2017-12-27 09:09 UTC, Ploypiti approved these changes

2017-12-27 09:10 UTC, saurabhjn76 approved these changes

2017-12-27 09:10 UTC, merged

2017-12-27 09:11 UTC, duttaditya18 commented
@saurabhjn76 Thanks!