Update index.html
fossasia/2016.fossasia.org pull request #151
Opened 2017-12-28 07:02 UTC by musakazem

Added social media links(Facebook)  to the following speakers:
Michael Cheng
Alexandre Lision
Anivar Aravind

2017-12-28 14:27 UTC, anshumanv requested changes
Check comments.

2017-12-28 14:27 UTC, anshumanv commented on index.html
> +											<a href="https://www.facebook.com/an1var/?hc_ref=ARTVpb1ckvX2lz1BR2n25Adv_rcR9NCUy4SAp7otRXabqihX8JFYa4vUlMKgfhCUm0s&fref=nf"><i class="icon social_facebook"></i></a>
Replace by this - https://www.facebook.com/an1var

2017-12-28 14:28 UTC, anshumanv commented
Please reference the issue that you're solving and update the PR title to what this PR actually does, same with the commit.

2018-01-03 18:33 UTC, akshatnitd reviewed
@musakazem Please make the requested changes so that we can merge it. Also, you need to resolve the conflicts!

2018-01-05 10:35 UTC, isuruAb reviewed
please resolve conflicts

2018-01-05 22:06 UTC, ParthS007 requested changes
@musakazem  Please resolve conflicts and update your PR.

2018-01-16 19:25 UTC, ParthS007 commented
closing due to inactivity 👍

2018-01-16 19:25 UTC, closed without merging